### ISSUE TITLE
Keycloak service triggers a shutdown after it went up for a couple of seconds.

### ISSUE THREAD

**Issue by MerNat** [sighupio/fury-kubernetes-keycloak#7]
I've configured and deployed this repository service(s) and found out that it wasn't successfully executed. Please find the logs here.

What it's doing it is once the keycloak service is up; it automatically got suspended (don't know why).

![](https://i.imgur.com/TbD751z.png)

**Comment by ralgozino** [comment]
Hi @MerNat 
I think your pod is taking too much time to come up and became ready, so the liveness or the readiness probe are failing. Could you please check that?

You can do that running:
`kubectl describe pod <your keycloak pod>`
Take a look at the events, and also please check the last state and reason field.

**Comment by MerNat** [comment]
Hello @ralgozino thank you for your reply. It's strange but it has worked perfectly when I bumped up the jboss/keycloak version to 9.0.3.

**Comment by ralgozino** [comment]
I'm glad you got it working. Thanks for letting us know.

I'm setting the issue as closed.
